AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.busqandote::busqandote-telegram
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  BusqandoteTelegramFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.busqandote.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: "s3://busqandote2-telegram/busqandote-telegram-1.0-SNAPSHOT-lambda-package.zip"
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30